### ISSUE TITLE
Feature request: NMcheckData look for periods

### ISSUE THREAD

**Issue by billdenney** [philipdelff/NMdata#28]
Most of the NONMEM data that I work with codes missing data as a period (".").  When I make an error with how I'm loading the data in R (mainly, when I'm not thinking about the loading carefully and just use `read.csv()` without modification), I will have those periods in the data.

I think it would be a useful feature to have `NMcheckData()` check and see if cells in the data have periods and suggest that maybe those should be converted to NA with code like `type_convert(data, na=c(".", "NA"))`.

**Comment by philipdelff** [comment]
Thanks Bill,

I agree, NMchecData should look for this. The default behavior of data reader functions in NMdata (like NMscanData, NMscanInput, NMreadCsv) is to interpret "." as NA, so if you use these functions to read delimited-text data files, this should not be an issue. If you however use NMscanData to combine output tables with input data stored in rds, the exact data object as prepared in R will be used, and then you will end up with "."'s in your resulting data set. 

NMwriteData codes NA's in the R data object as "." by default when writing csv files, so there really is no reason for the user to code the "." themselves. By contrast, that will make the rds file less useful as described above. So I agree, NMcheckData should look for "." in numerical columns. 

By the way, you can control what character strings NMdata translate to and interpret as NA when converting to and from csv by the args.fread and args.fwrite arguments to NMdataConf (which configures NMdata default behavior). The functions that handle this under the hood are data.table::fread and data.table::fwrite.

**Comment by philipdelff** [comment]
Having given this another thought, I am not sure what's the best way to handle it. If you load the input data with read.csv() and it contains "." for missing values, the affected columns should turn out character and not numeric. Is that the issue? Once you convert the columns to numeric, the "."s should become NA. 

If you use NMreadCsv() the columns should be numeric, and the "."s as NA. So as long as you use NMscanData() with use.rds=FALSE, there is no issue. There is however an issue if you want to use the rds input data file because then the data will not be converted back to numeric.

Right now, I am inclined to include a check for some standard columns (TIME, DV, AMT) to be numeric and not character. But people should do as they are most comfortable with, and if they are used to rounding to characters before saving the data, I don't want to tell them to change that. Rather, it's the use of an rds file that loses its advantage in this case. So we can include an argument to disable this check.

BTW, I would encode the missings as NA and let NMwriteData (fwrite) convert that to "." when writing the csv. I am not familiar with type_convert() but are you suggesting to encode them as the string "NA" and write that to the csv? I never tried but wouldn't think Nonmem can handle that.

**Comment by billdenney** [comment]
I understand the complexity here.

I think that my preference would be to test all columns:

* If numeric, do nothing.
* Have this controlled by an option, or make the warning classed so that it can be specifically suppressed (most people I know don't know how to suppress specific warnings, so that's more of a developer-focused feature, and it may not be the right fit):
    * If character (or factor), see if values could be either numeric or "."; give a warning suggesting that the user may want to convert.
    * Ensure that all columns are collected together so that there is only one warning given (not one warning per column).

That said, this is a subtle request and I wouldn't want it to make things harder to maintain unless you see value in it.

Aside:
`readr::type_convert()` converts the type of data in data.frames and similar objects to what is most likely the desired data type.  I use it pretty often, but it has some drawbacks.  The most notable drawback that I know of is that there are some types of data where conversion to numeric is not desired.  For me, that often happens with the `SUBJID` column of SDTM or SDTM-like data.  But, when it's helpful, it's a very quick tool to put data in the right format.  In this case, something like `readr::type_convert(data, na=".")` would do all of the conversions to numeric when NA is represented as a ".".

And, I wasn't intending to suggest writing `NA` values as the string `"NA"`.  I also don't think that NONMEM can handle that.

**Comment by philipdelff** [comment]
Sorry Bill, I am deferring this one for now.

It is common to code missing values with periods in Nonmem data sets, and NMwriteCsv does this when writing a csv for Nonmem.

The feature of saving the data set to an rds is useful if you don´t convert columns to character in R before writing data to files using NMwriteData. If one prefers to convert numeric columns to character columns and replacing NA's with periods manually (I don´t see any advantage of this approach), data has to be converted again for post-processing in R. NMreadCsv is available for that, and NMscanData will do it automatically. In this case, you probably want to call NMscanData with use.rds=FALSE.

In brevity, both ways are acceptable for Nonmem, and NMdata is already providing the tools to handle data coded in either way. I like NMdata does not create unnecessary new requirements on how people get the job done but just provides useful tools to make life easier. 

You are touching on some good points on how findings are reported. The idea is that NMcheckData collects a data set of all findings, but a good summary function is needed (so far, we just count number of occurrences of each finding type). Also, I'd love a function (or a set of such) to extract relevant subsets of data based on the findings for quick inspection/plotting.

**Comment by philipdelff** [comment]
Sorry Bill, I am deferring this one for now.

It is common to code missing values with periods in Nonmem data sets, and NMwriteCsv does this when writing a csv for Nonmem.

The feature of saving the data set to an rds is useful if you don´t convert columns to character in R before writing data to files using NMwriteData. If one prefers to convert numeric columns to character columns and replacing NA's with periods manually (I don´t see any advantage of this approach), data has to be converted again for post-processing in R. NMreadCsv is available for that, and NMscanData will do it automatically. In this case, you probably want to call NMscanData with use.rds=FALSE.

In brevity, both ways are acceptable for Nonmem, and NMdata is already providing the tools to handle data coded in either way. I like NMdata does not create unnecessary new requirements on how people get the job done but just provides useful tools to make life easier.

You are touching on some good points on how findings are reported. The idea is that NMcheckData collects a data set of all findings, but a good summary function is needed (so far, we just count number of occurrences of each finding type). Also, I'd love a function (or a set of such) to extract relevant subsets of data based on the findings for quick inspection/plotting.

**Comment by philipdelff** [comment]
closing

**Comment by philipdelff** [comment]
Sorry Bill, I am deferring this one for now.

It is common to code missing values with periods in Nonmem data sets, and NMwriteCsv does this when writing a csv for Nonmem.

The feature of saving the data set to an rds is useful if you don´t convert columns to character in R before writing data to files using NMwriteData. If one prefers to convert numeric columns to character columns and replacing NA's with periods manually (I don´t see any advantage of this approach), data has to be converted again for post-processing in R. NMreadCsv is available for that, and NMscanData will do it automatically. In this case, you probably want to call NMscanData with use.rds=FALSE.

In brevity, both ways are acceptable for Nonmem, and NMdata is already providing the tools to handle data coded in either way. I like NMdata does not create unnecessary new requirements on how people get the job done but just provides useful tools to make life easier.

You are touching on some good points on how findings are reported. The idea is that NMcheckData collects a data set of all findings, but a good summary function is needed (so far, we just count number of occurrences of each finding type). Also, I'd love a function (or a set of such) to extract relevant subsets of data based on the findings for quick inspection/plotting.

**Comment by philipdelff** [comment]
Sorry Bill, I am deferring this one for now.

It is common to code missing values with periods in Nonmem data sets, and NMwriteCsv does this when writing a csv for Nonmem.

The feature of saving the data set to an rds is useful if you don´t convert columns to character in R before writing data to files using NMwriteData. If one prefers to convert numeric columns to character columns and replacing NA's with periods manually (I don´t see any advantage of this approach), data has to be converted again for post-processing in R. NMreadCsv is available for that, and NMscanData will do it automatically. In this case, you probably want to call NMscanData with use.rds=FALSE.

In brevity, both ways are acceptable for Nonmem, and NMdata is already providing the tools to handle data coded in either way. I like NMdata does not create unnecessary new requirements on how people get the job done but just provides useful tools to make life easier.

You are touching on some good points on how findings are reported. The idea is that NMcheckData collects a data set of all findings, but a good summary function is needed (so far, we just count number of occurrences of each finding type). Also, I'd love a function (or a set of such) to extract relevant subsets of data based on the findings for quick inspection/plotting.

**Comment by billdenney** [comment]
That makes sense and. no worries at all.
