### ISSUE TITLE
new test failure using data.table github master

### ISSUE THREAD

**Issue by tdhock** [philipdelff/NMdata#40]
hi @philipdelff 
When I run R CMD check on NMdata with the new version of data.table from github master, I get the following new error which is not present when using data.table release version from CRAN:
```
* checking tests ...
  Running 'spelling.R'
  Running 'testthat.R'
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
   2.   \-testthat::expect_known_value(..., update = update)
  -- Failure ('test_NMscanInput.R:152'): CYCLE=DROP ------------------------------
  `nm1` has changed from known value recorded in 'testReference/NMscanInput_7.rds'.
  Component "input.colnames": Attributes: < Names: 1 string mismatch >
  Component "input.colnames": Attributes: < Length mismatch: comparison on first 2 components >
  Component "input.colnames": Attributes: < Component 2: Attributes: < target is NULL, current is list > >
  Component "input.colnames": Attributes: < Component 2: Numeric: lengths (24, 0) differ >
  Backtrace:
      x
   1. \-testthat::expect_equal_to_reference(nm1, fileRef, version = 2) at test_NMscanInput.R:152:4
   2.   \-testthat::expect_known_value(..., update = update)
  
  [ FAIL 6 | WARN 0 | SKIP 0 | PASS 210 ]
  Error: Test failures
  Execution halted
```
Looking at your tests, it seems that you expect that some computed value from your code is equal to the value stored in a RDS file. The `input.colnames` table has a new attribute named "index" which is causing the error, since the stored RDS value has no such attribute. 
Can you please update your tests and/or code so that this ERROR goes away, and then submit a new version to CRAN?
This will help facilitate releasing a new version of data.table to CRAN. (data.table devs must make sure all reverse dependencies do not break, before submitting a new version to CRAN)

**Comment by philipdelff** [comment]
Hi Dylan,

Whatever I can do not to be in the way for data.table. I am a huge fan of your work. 

However, how can I test against the new version of data.table you are referring to?

Thanks,
Philip

On November 26, 2022 9:46:06 AM EST, Toby Dylan Hocking ***@***.***> wrote:
>hi @philipdelff 
>When I run R CMD check on NMdata with the new version of data.table from github master, I get the following new error which is not present when using data.table release version from CRAN:
>```
>* checking tests ...
>  Running 'spelling.R'
>  Running 'testthat.R'
> ERROR
>Running the tests in 'tests/testthat.R' failed.
>Last 13 lines of output:
>   2.   \-testthat::expect_known_value(..., update = update)
>  -- Failure ('test_NMscanInput.R:152'): CYCLE=DROP ------------------------------
>  `nm1` has changed from known value recorded in 'testReference/NMscanInput_7.rds'.
>  Component "input.colnames": Attributes: < Names: 1 string mismatch >
>  Component "input.colnames": Attributes: < Length mismatch: comparison on first 2 components >
>  Component "input.colnames": Attributes: < Component 2: Attributes: < target is NULL, current is list > >
>  Component "input.colnames": Attributes: < Component 2: Numeric: lengths (24, 0) differ >
>  Backtrace:
>      x
>   1. \-testthat::expect_equal_to_reference(nm1, fileRef, version = 2) at test_NMscanInput.R:152:4
>   2.   \-testthat::expect_known_value(..., update = update)
>  
>  [ FAIL 6 | WARN 0 | SKIP 0 | PASS 210 ]
>  Error: Test failures
>  Execution halted
>```
>Looking at your tests, it seems that you expect that some computed value from your code is equal to the value stored in a RDS file. The `input.colnames` table has a new attribute named "index" which is causing the error, since the stored RDS value has no such attribute. 
>Can you please update your tests and/or code so that this ERROR goes away, and then submit a new version to CRAN?
>This will help facilitate releasing a new 

version of data.table to CRAN. (data.table devs must make sure all reverse dependencies do not break, before submitting a new version to CRAN)
>

**Comment by tdhock** [comment]
Hi! The new data.table code is in the master branch on github, https://github.com/Rdatatable/data.table/
You can install it via `remotes::install_github("Rdatatable/data.table")` or `data.table::update_dev_pkg()`
(by the way my first name, and the usual name that people call me, is Toby)

**Comment by tdhock** [comment]
In your test code, I would suggest removing expect_equal_to_reference (which is overly specific, causes test failures for some cases/changes which are not actually problematic) and instead using expect_equal for the specific list elements / data table columns that you are looking for (less likely to cause false test failures like this one).

**Comment by philipdelff** [comment]
Hi Toby,

I believe this is now fixed in master by ensuring that those specific data.tables will not have indices even when using earlier versions of data.table. All tests seem to pass now using the master branch of data.table. If I don't hear anything back from you, I will submit this to CRAN in the coming days.

Thanks,
Philip

**Comment by tdhock** [comment]
great thanks!

**Comment by tdhock** [comment]
I confirm this failure no longer happens.
