### ISSUE TITLE
more precise duplicate checking

### ISSUE THREAD

**Issue by andersone1** [philipdelff/NMdata#42]
Hello,

My name is Eric Anderson and I work at Metrum Research Group as a Data Scientist. For starters, I just want to mention that I find this package very interesting and useful.

The function I have been exploring the most is `NMdata::NMcheckData()`.

I have a potential feature request regarding the duplicate checking. It seems like right now the function checks across these columns`ID, CMT, EVID, TIME`.

Sometimes I work with data sets that have additional columns that define unique rows (e.g. `DVID`, `DRUGID`, etc). Have you considered adding an argument to the function that allows for this?

**Comment by philipdelff** [comment]
Thanks Eric,

I'm glad you are finding NMdata useful. If you go over the cheatsheet you may find more interesting functions.

Your suggestion would be easy to add. In fact, the way NMcheckData is designed it's easy to add/improve checks.

What do you think would be the most useful design? An argument that defines additional columns to include in the search for duplicates? Or one that defines them from scratch?

**Comment by andersone1** [comment]
@philipdelff ,

That's a good question. At first thought, I like it how it automatically adds `col.id, col.cmt, col.evid, col.time` to the duplicate check, so I would not want to have to define that each time. An argument allowing to define to additional columns in the search for duplicates sounds better to me.

**Comment by philipdelff** [comment]
@andersone1,

This is now implemented as an argument called `cols.dup` in the master branch. Closing the issue for now. Feel free to reopen it if this is insufficient.

**Comment by andersone1** [comment]
@philipdelff 

This is a great solution, thank you. 

Do you have an expectation on when a version of this package will be published to CRAN that includes this function?

**Comment by philipdelff** [comment]
@andersone1 
Funny you ask today, I just started preparing for it. I should be able to get it in next week.

**Comment by philipdelff** [comment]
@andersone1 
Feel free to make a pull request with any tests you want included if you have some specific cases you want the function to be able to handle.

**Comment by andersone1** [comment]
@philipdelff  Can you give me contributor status on Git? (under settings)

**Comment by andersone1** [comment]
@philipdelff 

This might be quicker for the time being - here is the code for the test (can you please add this to the bottom of `tests/testthat/test_NMcheckData.R`):


```
dups_data <- data.frame(
  ID = c(1, 1, 1),
  TIME = c(1, 2, 2),
  DV = c(NA, 20, 50),
  AMT = c(100, 0, 0),
  EVID = c(1, 0, 0),
  DVID = c(1, 2, 3),
  ROW = 1:3,
  CMT = 1,
  MDV = c(0, 0, 0)
)


test_that("check data files without cols.dup, but passed with it",{
  no_dup_specified <- NMcheckData(dups_data)
  dup_specified <- NMcheckData(dups_data, cols.dup = "DVID")
  
  expect_equal(nrow(no_dup_specified), 2)
  expect_equal(nrow(dup_specified), 0)
})

```

**Comment by philipdelff** [comment]
Thank you!

You don't need to be collaborator - you can do a pull request. I am also happy to put this in. Up to you how we do it.

**Comment by andersone1** [comment]
@philipdelff 

Sounds good - I made a PR here:

https://github.com/philipdelff/NMdata/pull/43
