### ISSUE TITLE
Compatibility with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [philipdelff/NMdata#45]
This package no longer passes its checks with the current tibble release candidate, perhaps triggered by https://github.com/tidyverse/tibble/pull/1574 (now keeping attributes named `"x"` and `"n"`  after `new_tibble()` and `as_tibble()`). Please see https://github.com/tidyverse/tibble/blob/main/revdep/problems.md#nmdata for details.

Should we be doing things differently? Can you please take a look and, if appropriate, submit an update to CRAN? Thanks!

**Comment by philipdelff** [comment]
Thank you. The test has been generalized and is no longer affected by the change in tibble. I plan to submit to CRAN within a week.

**Comment by philipdelff** [comment]
Version 0.1.6 is now on CRAN. It should work with the new version of tibble.
Thanks!
